[project]
name = "test-remote-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rishee3105", email = "risheegandhi3105@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=3.4.7",
]

[project.scripts]
test-remote-server = "test_remote_server:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
